name: Bug Report
description: Report broken or incorrect behaviour
labels: unconfirmed bug
body:
  - type: markdown
    attributes:
      value: >
        Please note that this is only a bug report form for **this repo only**.
        Bug reports for internal library errors must be reported to https://github.com/Pycord-Development/pycord
        
        `ALL UNNECESSARY BUG REPORTS WILL BE DELETED`
  - type: input
    attributes:
      label: Summary
      description: A simple summary of your bug report
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code
      description: >
        What code did you use to cause this error?
      render: python
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal Reproducible Code
      description: >
        A short snippet of code that showcases the bug.
      render: python
  - type: textarea
    attributes:
      label: Expected Results
      description: >
        What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Results
      description: >
        What actually happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Py-cord Version
      description: >
        Run `python -m discord -v` and paste this information below.
        You can also print out `discord.__version__` to get the version itself then paste it here
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: If there is anything else to say, please do so here.
