name: Feature Request
description: Suggest a feature for this py-cord examples repo.
labels: feature request
body:
  - type: markdown
    attributes:
      value: >
        Please note that this is only a bug report form for **this repo only**.
        Bug reports for internal library errors must be reported to https://github.com/Pycord-Development/pycord
        
        `ALL UNNECESSARY BUG REPORTS WILL BE DELETED`
  - type: input
    attributes:
      label: Summary
      description: >
        A short summary of what your feature request is.
    validations:
      required: true
  - type: dropdown
    attributes:
      multiple: false
      label: What is the feature request for?
      options:
        - Views
        - Moderation
        - Utility
    validations:
      required: true
  - type: textarea
    attributes:
      label: Problem
      description: >
        What problem is your feature trying to solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution
      description: >
        What would you like this feature to do?
    validations:
      required: true
  - type: textarea
    attributes:
      label: The Current Solution
      description: >
        What is the current solution to the problem, if any?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Want to add anything else? Do it here
